
/*
 * File Created: Wednesday, 26th December 2018 7:14:52 pm
 * Last Modified: Wednesday, 16th January 2019 10:08:53 am
 * Author: Charlene Leong (charleneleong84@gmail.com)
 */

crane_plus:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - crane_plus_shoulder_revolute_joint
    - crane_plus_shoulder_flex_joint
    - crane_plus_elbow_joint
    - crane_plus_wrist_joint
crane_plus_finger:
  type: "effort_controllers/JointPositionController"
  joint: crane_plus_moving_finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
