crane_plus:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - crane_plus_shoulder_revolute_joint
    - crane_plus_shoulder_flex_joint
    - crane_plus_elbow_joint
    - crane_plus_wrist_joint
crane_plus_finger:
  type: "effort_controllers/JointPositionController"
  joint: crane_plus_moving_finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
