crane_plus:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - crane_plus_shoulder_revolute_joint
    - crane_plus_shoulder_flex_joint
    - crane_plus_elbow_joint
    - crane_plus_wrist_joint
  gains: # Required because we're controlling an velocity interface
    crane_plus_shoulder_revolute_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
    crane_plus_shoulder_flex_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
    crane_plus_elbow_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
    crane_plus_wrist_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
  constraints:
      goal_time: 0.25
      stopped_velocity_tolerance: 0.05
      arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      arm_elbow_flex_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_flex_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  
crane_plus_finger:
  type: "effort_controllers/JointPositionController"
  joint: crane_plus_moving_finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
  

